Fix GPS output
The GPS output wasn't converted to a string, so eventually get_summary in pynagPlugins would fail with:
TypeError: sequence item 0: expected str instance, bytes found